version: "3.9"
services:

#  recommendation:
#    build: .
#    ports:
#      - "5000:5000"
#    environment:
#      FLASK_APP: app
#      FLASK_DEBUG: 1
  recommendation-db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recommendation
      POSTGRES_PASSWORD: recommendation
      POSTGRES_DB: recommendation
    volumes:
      - ./volumes/recommendation-db:/var/lib/postgresql/data
  s3:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./volumes/s3-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: S3_ADMIN_PASSWD
    command: server /data --console-address ":9001"
