openapi: 3.0.2
info:
  title: recommendation
  version: '1.1'
paths:
  /recommendations/{dancerId}:
    get:
      parameters:
        - in: path
          name: dancerId
          schema:
            type: string
          required: true
          description: the dancerId for which we computed the recommendations
      responses:
        '200':
          description: 'the computed responses'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recommendations_response'

components:
  schemas:
    recommendations_response:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            enum:
              - DANCER
              - SCHOOL
              - EVENT
              - SHOP
              - ETC
            example: DANCER
          dancerVersion:
            type: integer
            description: version of the dancers' profile
            example: 1
          targedId:
            type: string
            description: the id of the recommended item. In case of a recommended dancer this would be the dancerId
            example: f05fa3d2-62ab-11ed-a60b-abb65ae72838
          targetVersion:
            type: integer
            description: version of the recommended resource (if available)
            example: 34
          score:
            type: integer
            description: Number between 0 and 100. 0 would mean does not fit at all, while 100 is kind of perfect fit.
            example: 64
