openapi: 3.0.2
info:
  title: recommendation
  version: '1.1'
paths:
  /recommendations/{dancerId}:
    get:
      parameters:
        - in: path
          name: dancerId
          schema:
            type: string
          required: true
          description: the dancerId for which we computed the recommendations
      responses:
        '200':
          description: 'the computed responses'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/recommendations_response'

components:
  schemas:
    recommendations_response:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
            enum:
              - DANCER
              - SCHOOL
              - EVENT
              - SHOP
              - ETC
            example: DANCER
          recommendationId:
            type: string
            description: identifier for one concrete recommendation.
          recommendationTime:
            type: string
            description: when this concrete recommendation has been computed.
          targedId:
            type: string
            description: the id of the recommended item. In case of a recommended dancer this would be the dancerId
          targedTime:
            type: string
            description: the time of the last update of the recommendated resource. In case of a dancer this would be his last profile update
          score:
            type: integer
            description: Number between 0 and 100. 0 would mean does not fit at all, while 100 is kind of perfect fit.
