name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Login to the Docker registry
        run:  docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build the Docker image
        run:  docker build -t dancier/recommendation:$(git rev-parse --short "$GITHUB_SHA") -t dancier/recommendation:latest .
      - name: Publish the Docker image on hub.docker.com
        run:  docker push -a dancier/recommendation
