name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Build the Docker image
        run:  docker build -t dancier/recommendation:$(git rev-parse --short "$GITHUB_SHA") -t dancier/recommendation:latest .
      - name: Publish the Docker image on hub.docker.com
        run:  docker push -a dancier/recommendation
